### ISSUE TITLE
Fix needed for Core OS bug

### ISSUE THREAD

**Issue by petemoore** [mozilla-services/hawk-go#12]
See https://github.com/taskcluster/taskcluster/pull/2715#issuecomment-618687648

**Comment by jvehent** [comment]
Happy to take a patch for this. 👍

**Comment by jvehent** [comment]
_(involuntary click on "close", this is definitely remaining open)_

**Comment by Alexander-r** [comment]
Would it be enough to replace req.URL.Path with req.URL.EscapedPath() in extractRequestURI to fix this?
It fixes the Path part of the URI and the result becomes identical to the one produced by url.ReuqestURI(). But I am uncertain about the req.URL.RawQuery part. Should we encode it? Is it already encoded?
